include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    todo: warning
    deprecated_member_use: warning
    missing_return: error
    unused_import: error

linter:
  rules:
    # General code quality
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    prefer_interpolation_to_compose_strings: true
    prefer_const_declarations: true
    avoid_returning_null_for_future: true

    # Test and QA specific
    avoid_empty_else: true
    empty_statements: true

    # Relaxed for readability
    lines_longer_than_80_chars: false

    # Warnings for debug-only code
    avoid_print: true

